# Generated by Django 3.0.2 on 2020-03-08 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200305_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_products',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Order'),
        ),
        migrations.AlterField(
            model_name='order_products',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Product'),
        ),
    ]
