# Generated by Django 3.0.2 on 2020-03-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_my_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_cart',
            old_name='product',
            new_name='products',
        ),
    ]
