# Generated by Django 3.0.2 on 2020-03-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_cart',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
